# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.24
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: true
odoo_test_flavor: Odoo
odoo_version: 16.0
org_name: Omegasoft C.A.
org_slug: OCA
rebel_module_groups: []
repo_description: Odoo modules for Venezuela
repo_name: Odoo modules for Venezuela
repo_slug: Closter_l10n_ve
repo_website: https://github.com/macagua/Closter_l10n_ve
use_pyproject_toml: true
use_ruff: true

