
target-version = "py310"
fix = true

[lint]
extend-select = [
    "B",
    "C90",
    "E501",  # line too long (default 88)
    "I",  # isort
    "UP",  # pyupgrade
]
exclude = ["setup/*"]

[format]
exclude = ["setup/*"]

[per-file-ignores]
"__init__.py" = ["F401", "I001"]  # ignore unused and unsorted imports in __init__.py
"__manifest__.py" = ["B018"]  # useless expression

[isort]
section-order = ["future", "standard-library", "third-party", "odoo", "odoo-addons", "first-party", "local-folder"]

[isort.sections]
"odoo" = ["odoo"]
"odoo-addons" = ["odoo.addons"]

[mccabe]
max-complexity = 16

[lint.per-file-ignores]
"hr_organizational_chart/__manifest__.py" = ["B018"]
"l10n_ve_account_reports_dual/__manifest__.py" = ["B018"]
"l10n_ve_account_reports_dual/models/account_aged_partner_balance.py" = ["E501"]
"l10n_ve_account_reports_dual/models/account_cash_flow_report.py" = ["E501"]
"l10n_ve_account_reports_dual/models/account_general_ledger.py" = ["E501"]
"l10n_ve_account_reports_dual/models/account_generic_tax_report.py" = ["E501"]
"l10n_ve_account_reports_dual/models/account_journal_report.py" = ["E501"]
"l10n_ve_account_reports_dual/models/account_move_line_tax_details.py" = ["E501"]
"l10n_ve_account_reports_dual/models/account_multicurrency_revaluation_report.py" = ["E501"]
"l10n_ve_account_reports_dual/models/account_partner_ledger.py" = ["E501"]
"l10n_ve_account_reports_dual/models/account_report.py" = ["E501"]
"l10n_ve_account_reports_dual/models/product_product.py" = ["E501"]
"l10n_ve_account_sale_reports/__manifest__.py" = ["B018"]
"l10n_ve_account_sale_reports/report/account_invoice_report.py" = ["E501"]
"l10n_ve_account_sale_reports/report/sale_report.py" = ["E501"]
"l10n_ve_arc_report/__manifest__.py" = ["B018"]
"l10n_ve_arc_report/models/account_arc_report.py" = ["E501"]
"l10n_ve_config_account/__manifest__.py" = ["B018"]
"l10n_ve_config_account/models/account_move.py" = ["E501"]
"l10n_ve_config_withholding/__manifest__.py" = ["B018"]
"l10n_ve_dual_currency/__manifest__.py" = ["B018"]
"l10n_ve_dual_currency/models/account_move.py" = ["E501"]
"l10n_ve_dual_currency/models/account_move_line.py" = ["E501"]
"l10n_ve_dual_currency/models/product_product.py" = ["E501"]
"l10n_ve_dual_currency/models/res_currency.py" = ["E501"]
"l10n_ve_dual_currency_export/__manifest__.py" = ["B018"]
"l10n_ve_fiscal_book_report/__manifest__.py" = ["B018"]
"l10n_ve_fiscal_book_report/models/account_fiscal_books.py" = ["E501"]
"l10n_ve_fiscal_identification/__manifest__.py" = ["B018"]
"l10n_ve_fiscal_identification/models/partner_domain.py" = ["E501"]
"l10n_ve_gross_income_report/__manifest__.py" = ["B018"]
"l10n_ve_kardex_report/__manifest__.py" = ["B018"]
"l10n_ve_kardex_report/models/account_kardex_report.py" = ["E501"]
"l10n_ve_sale_sequence/__manifest__.py" = ["B018"]
"l10n_ve_sale_sequence/models/account_sale_sequence.py" = ["E501"]
"l10n_ve_withholding_igtf/__manifest__.py" = ["B018"]
"l10n_ve_withholding_igtf/models/account_payment.py" = ["E501"]
"l10n_ve_withholding_islr/__manifest__.py" = ["B018"]
"l10n_ve_withholding_islr/models/account_move.py" = ["E501"]
"l10n_ve_withholding_islr/models/product_template.py" = ["E501"]
"l10n_ve_withholding_islr/models/res_config_settings.py" = ["E501"]
"l10n_ve_withholding_itf/__manifest__.py" = ["B018"]
"l10n_ve_withholding_itf/models/res_company.py" = ["E501"]
"l10n_ve_withholding_iva/__manifest__.py" = ["B018"]
"l10n_ve_withholding_iva/models/account_move.py" = ["E501", "F841"]
"l10n_ve_withholding_iva/models/res_config_settings.py" = ["E501"]
"l10n_ve_withholding_municipal/__manifest__.py" = ["B018"]
"l10n_ve_withholding_municipal/models/account_move.py" = ["E501"]
"l10n_ve_withholding_municipal/models/res_config_settings.py" = ["E501"]
"l10n_ve_withholding_tax_liquor/__manifest__.py" = ["B018"]
"l10n_ve_withholding_tax_liquor/models/account_liquor_tax_report.py" = ["E501"]
"omegasoft_contract_social_benefit_liabilities_fields/__manifest__.py" = ["B018"]
"omegasoft_contract_social_benefit_liabilities_fields/models/models.py" = ["E501", "B023"]
"omegasoft_contract_allocation/__manifest__.py" = ["B018"]
"omegasoft_contract_benefit_controls_fields/__manifest__.py" = ["B018"]
"omegasoft_contract_bonuses_fields/__manifest__.py" = ["B018"]
"omegasoft_contract_employee_seniority/__manifest__.py" = ["B018"]
"omegasoft_contract_parafiscal_contributions_fields/__manifest__.py" = ["B018"]
"omegasoft_contract_salary_fields/__manifest__.py" = ["B018"]
"omegasoft_contract_utility_liabilities_fields/__manifest__.py" = ["B018"]
"omegasoft_contract_vacations_fields/__manifest__.py" = ["B018"]
"omegasoft_employee_arc/__manifest__.py" = ["B018"]
"omegasoft_employee_arc/models/hr_employee.py" = ["E501"]
"omegasoft_employee_ari/__manifest__.py" = ["B018"]
"omegasoft_employee_eventual_bonuses/__manifest__.py" = ["B018"]
"omegasoft_export_payroll_payments/__manifest__.py" = ["B018"]
"omegasoft_export_payroll_payments/models/export_bank_payments.py" = ["E501", "UP030"]
"omegasoft_export_payroll_payments_banavih/__manifest__.py" = ["B018"]
"omegasoft_export_payroll_payments_banavih/models/models.py" = ["E501"]
"omegasoft_hr_employee/__manifest__.py" = ["B018"]
"omegasoft_hr_employee_advances_automated_amounts/__manifest__.py" = ["B018"]
"omegasoft_hr_employee_advances_automated_amounts/models/hr_employee_advances_loans_discounts.py" = ["E501"]
"omegasoft_hr_employee_advances_loans_discounts/__manifest__.py" = ["B018"]
"omegasoft_hr_employee_advances_loans_discounts/models/hr_employee_advances_loans_discounts_lines.py" = ["E501"]
"omegasoft_hr_employee_badge/__manifest__.py" = ["B018"]
"omegasoft_hr_employee_bank_information/__manifest__.py" = ["B018"]
"omegasoft_hr_employee_code/__manifest__.py" = ["B018"]
"omegasoft_hr_employee_code/__init__.py" = ["E501"]
"omegasoft_hr_employee_crew/__manifest__.py" = ["B018"]
"omegasoft_hr_employee_disability/__manifest__.py" = ["B018"]
"omegasoft_hr_employee_disability/models/canapdis.py" = ["E501"]
"omegasoft_hr_employee_family_information/__manifest__.py" = ["B018"]
"omegasoft_hr_estimated_profits/__manifest__.py" = ["B018"]
"omegasoft_hr_estimated_profits/models/lines_estimated_profit.py" = ["E501"]
"omegasoft_hr_hcm/__manifest__.py" = ["B018"]
"omegasoft_hr_hcm/models/hr_hcm_coverage_scale.py" = ["B023"]
"omegasoft_hr_holidays/__manifest__.py" = ["B018"]
"omegasoft_hr_organizational_units/__manifest__.py" = ["B018"]
"omegasoft_hr_payroll/__manifest__.py" = ["B018"]
"omegasoft_hr_payroll/models/hr_payroll_payslips_by_employees.py" = ["E501"]
"omegasoft_hr_payroll/models/hr_payslip_run.py" = ["E501"]
"omegasoft_hr_payroll/models/hr_payslip_worked_days.py" = ["E501"]
"omegasoft_hr_payroll/models/hr_payslip.py" = ["E501", "B023"]
"omegasoft_res_currency_payroll_rate/__manifest__.py" = ["B018"]
"omegasoft_salary_bonuses_fields/__manifest__.py" = ["B018"]
"omegasoft_sale_commissions/__manifest__.py" = ["B018"]
"omegasoft_sale_commissions/models/account_move.py" = ["E501"]
"omegasoft_provisions_employee_report/__manifest__.py" = ["B018"]
"omegasoft_provisions_employee_report/report/hr_employee_provisions_report.py" = ["E501"]
"omegasoft_hr_payroll_receipt_payment/__manifest__.py" = ["B018"]
"omegasoft_hr_payroll_report_customization/__manifest__.py" = ["B018"]
"omegasoft_hr_plan_accumulation_vacation/__manifest__.py" = ["B018"]
"omegasoft_hr_plan_accumulation_vacation/models/hr_leave.py" = ["F841", "B023"]
"omegasoft_hr_report_letters/__manifest__.py" = ["B018"]
"omegasoft_hr_report_letters/wizard/hr_report_letters.py" = ["F841"]
"omegasoft_payroll_automatic_rule_code/__manifest__.py" = ["B018"]
"omegasoft_payroll_planning/__manifest__.py" = ["B018"]
"omegasoft_payroll_planning/models/plannig_slot.py" = ["F841"]
"omegasoft_payroll_res_config_settings/__manifest__.py" = ["B018"]
"omegasoft_payroll_salary_rules_report/__manifest__.py" = ["B018"]
"omegasoft_payroll_salary_rules_report/models/hr_payroll_report.py" = ["E501"]
"pways_so_po_consignment/__manifest__.py" = ["B018"]
"pways_so_po_consignment/models/picking.py" = ["B023"]
"pways_so_po_consignment/models/purchase.py" = ["B023"]
"pways_so_po_consignment/models/purchase_picking.py" = ["B023"]
"pways_so_po_consignment/models/purchase_sale.py" = ["B023"]
"pways_so_po_consignment/models/sale.py" = ["B023"]
"pways_so_po_consignment/models/sale_consignment_order.py" = ["E501", "B023"]
"pways_so_po_consignment/models/stock_warehouse.py" = ["E501"]
"pways_so_po_consignment/models/sale_consignment_line_lot_serial.py" = ["B023"]
"pways_so_po_consignment/wizard/sale_order_create_wizard.py" = ["F841"]
"pways_so_po_consignment/wizard/consignment_report_wizard.py" = ["B023"]
