import setuptools

with open('VERSION.txt', 'r') as f:
    version = f.read().strip()

setuptools.setup(
    name="odoo-addons-oca-l10n-venezuela",
    description="Meta package for oca-l10n-venezuela Odoo addons",
    version=version,
    # install_requires=[
    #     'odoo-addon-l10n_ve_account_reports_dual',
    #     'odoo-addon-l10n_ve_account_sale_reports',
    #     'odoo-addon-l10n_ve_arc_report',
    #     'odoo-addon-l10n_ve_config_account',
    #     'odoo-addon-l10n_ve_config_withholding',
    #     'odoo-addon-l10n_ve_dual_currency',
    #     'odoo-addon-l10n_ve_dual_currency_export',
    #     'odoo-addon-l10n_ve_fiscal_book_report',
    #     'odoo-addon-l10n_ve_fiscal_identification',
    #     'odoo-addon-l10n_ve_gross_income_report',
    #     'odoo-addon-l10n_ve_kardex_report',
    #     'odoo-addon-l10n_ve_sale_sequence',
    #     'odoo-addon-l10n_ve_withholding_igtf',
    #     'odoo-addon-l10n_ve_withholding_islr',
    #     'odoo-addon-l10n_ve_withholding_itf',
    #     'odoo-addon-l10n_ve_withholding_iva',
    #     'odoo-addon-l10n_ve_withholding_municipal',
    #     'odoo-addon-l10n_ve_withholding_tax_liquor',
    #     'odoo-addon-omegasoft_contract_allocation',
    #     'odoo-addon-omegasoft_contract_benefit_controls_fields',
    #     'odoo-addon-omegasoft_contract_bonuses_fields',
    #     'odoo-addon-omegasoft_contract_employee_seniority',
    #     'odoo-addon-omegasoft_contract_parafiscal_contributions_fields',
    #     'odoo-addon-omegasoft_contract_salary_fields',
    #     'odoo-addon-omegasoft_contract_social_benefit_liabilities_fields',
    #     'odoo-addon-omegasoft_contract_utility_liabilities_fields',
    #     'odoo-addon-omegasoft_contract_vacations_fields',
    #     'odoo-addon-omegasoft_employee_arc',
    #     'odoo-addon-omegasoft_employee_ari',
    #     'odoo-addon-omegasoft_employee_eventual_bonuses',
    #     'odoo-addon-omegasoft_export_payroll_payments',
    #     'odoo-addon-omegasoft_export_payroll_payments_banavih',
    #     'odoo-addon-omegasoft_hr_employee',
    #     'odoo-addon-omegasoft_hr_employee_advances_automated_amounts',
    #     'odoo-addon-omegasoft_hr_employee_advances_loans_discounts',
    #     'odoo-addon-omegasoft_hr_employee_badge',
    #     'odoo-addon-omegasoft_hr_employee_bank_information',
    #     'odoo-addon-omegasoft_hr_employee_code',
    #     'odoo-addon-omegasoft_hr_employee_crew',
    #     'odoo-addon-omegasoft_hr_employee_disability',
    #     'odoo-addon-omegasoft_hr_employee_family_information',
    #     'odoo-addon-omegasoft_hr_estimated_profits',
    #     'odoo-addon-omegasoft_hr_hcm',
    #     'odoo-addon-omegasoft_hr_holidays',
    #     'odoo-addon-omegasoft_hr_organizational_units',
    #     'odoo-addon-omegasoft_hr_payroll',
    #     'odoo-addon-omegasoft_hr_payroll_receipt_payment',
    #     'odoo-addon-omegasoft_hr_payroll_report_customization',
    #     'odoo-addon-omegasoft_hr_plan_accumulation_vacation',
    #     'odoo-addon-omegasoft_hr_report_letters',
    #     'odoo-addon-omegasoft_payroll_automatic_rule_code',
    #     'odoo-addon-omegasoft_payroll_planning',
    #     'odoo-addon-omegasoft_payroll_res_config_settings',
    #     'odoo-addon-omegasoft_payroll_salary_rules_report',
    #     'odoo-addon-omegasoft_provisions_employee_report',
    #     'odoo-addon-omegasoft_res_currency_payroll_rate',
    #     'odoo-addon-omegasoft_salary_bonuses_fields',
    #     'odoo-addon-omegasoft_sale_commissions',
    # ],
    classifiers=[
        'Programming Language :: Python',
        'Framework :: Odoo',
        'Framework :: Odoo :: 16.0',
    ]
)

